project_id = "cltytxckwretwrqfxdqf"

[functions.processar-produtos-ia]
verify_jwt = true

[functions.criar-organizacao]
verify_jwt = true

[functions.woovi-pix]
verify_jwt = true

[functions.woovi-webhook]
verify_jwt = false

[functions.woovi-check-status]
verify_jwt = true
